/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import javax.swing.JOptionPane;

import br.ulbra.entity.TrablhoLucas;

/**
 *
 * @author aluno.saolucas
 */
public class FrLista extends javax.swing.JFrame {

    /**
     * Creates new form FrLista
     */
    public FrLista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TXTperfume = new javax.swing.JTextField();
        BTNsalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTlista = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        TXTCodigo = new javax.swing.JTextField();
        BTNAlterar = new javax.swing.JButton();
        BTNApagar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TXTNovoPerfume = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TXTCodigoEx = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BTNQuantidade = new javax.swing.JButton();
        BTNlimpar = new javax.swing.JButton();
        BNTOrgnizar = new javax.swing.JButton();
        BNTListar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TXTProcurar = new javax.swing.JTextField();
        BTNProcurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nome do Perfume");

        TXTperfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTperfumeActionPerformed(evt);
            }
        });

        BTNsalvar.setBackground(new java.awt.Color(0, 255, 0));
        BTNsalvar.setText("SALVAR");
        BTNsalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTNsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsalvarActionPerformed(evt);
            }
        });

        TXTlista.setColumns(20);
        TXTlista.setRows(5);
        TXTlista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(TXTlista);

        jLabel3.setText("Código do Perfume");

        TXTCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCodigoActionPerformed(evt);
            }
        });

        BTNAlterar.setBackground(new java.awt.Color(255, 255, 255));
        BTNAlterar.setText("ALTERAR");
        BTNAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTNAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAlterarActionPerformed(evt);
            }
        });

        BTNApagar.setBackground(new java.awt.Color(255, 0, 0));
        BTNApagar.setText("EXCLUIR");
        BTNApagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTNApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNApagarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Alterar Perfume");

        TXTNovoPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNovoPerfumeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("PERFUMES LISTADOS");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setBackground(new java.awt.Color(0, 51, 255));
        jLabel11.setFont(new java.awt.Font("Gigi", 3, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("Flor de Essência");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Perfume Novo");

        jLabel7.setText("Código");

        TXTCodigoEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCodigoExActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Excluir Perfume");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Opcionais");

        BTNQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        BTNQuantidade.setText("QUANTIDADE");
        BTNQuantidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTNQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNQuantidadeActionPerformed(evt);
            }
        });

        BTNlimpar.setBackground(new java.awt.Color(255, 0, 0));
        BTNlimpar.setText("LIMPAR LISTA");
        BTNlimpar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTNlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlimparActionPerformed(evt);
            }
        });

        BNTOrgnizar.setBackground(new java.awt.Color(255, 255, 255));
        BNTOrgnizar.setText("ORDENAR");
        BNTOrgnizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BNTOrgnizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNTOrgnizarActionPerformed(evt);
            }
        });

        BNTListar.setBackground(new java.awt.Color(255, 255, 255));
        BNTListar.setText("LISTAR");
        BNTListar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BNTListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNTListarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Pesquisar");

        TXTProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTProcurarActionPerformed(evt);
            }
        });

        BTNProcurar.setBackground(new java.awt.Color(255, 255, 255));
        BTNProcurar.setText("PROCURAR");
        BTNProcurar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTNProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNProcurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 852, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TXTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BTNAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TXTCodigoEx, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BTNApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BTNQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTNovoPerfume, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                    .addComponent(TXTperfume))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TXTProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(BTNlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(299, 299, 299))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(BNTOrgnizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BNTListar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel5)))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNlimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BNTOrgnizar)
                            .addComponent(BNTListar))
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTperfume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNsalvar))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNAlterar))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTNovoPerfume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTCodigoEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNApagar))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(13, 13, 13)
                        .addComponent(BTNQuantidade)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNProcurar))
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTperfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTperfumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTperfumeActionPerformed
    TrablhoLucas bancoDeDados = new TrablhoLucas();

    private void BTNsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsalvarActionPerformed
        bancoDeDados.salvar(TXTperfume.getText());
        TXTlista.setText(bancoDeDados.listar());
    }//GEN-LAST:event_BTNsalvarActionPerformed

    private void TXTCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCodigoActionPerformed

    private void BTNAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAlterarActionPerformed
        bancoDeDados.alterar(Integer.parseInt(TXTCodigo.getText()), TXTNovoPerfume.getText());
        TXTlista.setText(bancoDeDados.listar());
    }//GEN-LAST:event_BTNAlterarActionPerformed

    private void BTNApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNApagarActionPerformed
        bancoDeDados.excluir(Integer.parseInt(TXTCodigoEx.getText()));
        TXTlista.setText(bancoDeDados.listar());
    }//GEN-LAST:event_BTNApagarActionPerformed

    private void TXTNovoPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNovoPerfumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNovoPerfumeActionPerformed

    private void TXTCodigoExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCodigoExActionPerformed
        bancoDeDados.excluir(Integer.parseInt(TXTCodigo.getText()));
        TXTlista.setText(bancoDeDados.listar());
    }//GEN-LAST:event_TXTCodigoExActionPerformed

    private void BTNQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNQuantidadeActionPerformed
        int quantidade = bancoDeDados.quantidade();
        JOptionPane.showMessageDialog(null, "Total de produtos: " + quantidade);

    }//GEN-LAST:event_BTNQuantidadeActionPerformed

    private void BTNlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlimparActionPerformed
        bancoDeDados.limparLista();
        TXTlista.setText("");
    }//GEN-LAST:event_BTNlimparActionPerformed

    private void BNTOrgnizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNTOrgnizarActionPerformed

    bancoDeDados.ordenarAlfabeticamente();

  
    StringBuilder listaFinal = new StringBuilder("Lista de produtos ordenada:\n");
    bancoDeDados.listaarrumado .forEach((produto) -> {
        listaFinal.append(produto).append("\n");
        });

   
    TXTlista.setText(listaFinal.toString());
    }//GEN-LAST:event_BNTOrgnizarActionPerformed

    private void BNTListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNTListarActionPerformed
        bancoDeDados.resetarLista();

  
    StringBuilder listaFinal = new StringBuilder("Lista de produtos na ordem original:\n");
    for (String produto : bancoDeDados.listaIdeal) {
        listaFinal.append(produto).append("\n");
    }

   
    TXTlista.setText(listaFinal.toString());;    }//GEN-LAST:event_BNTListarActionPerformed

    private void TXTProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTProcurarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTProcurarActionPerformed

    private void BTNProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNProcurarActionPerformed
        String produtoBuscado = TXTProcurar.getText().trim();  

   
    if (!produtoBuscado.isEmpty()) {
        boolean encontrado = false; 

       
        for (String produto : bancoDeDados.listaarrumado) {
           
            if (produto.equalsIgnoreCase(produtoBuscado)) {
                JOptionPane.showMessageDialog(null, "Produto encontrado: " + produto);
                encontrado = true;
                break; 
            }
        }

      
        if (!encontrado) {
            JOptionPane.showMessageDialog(null, "Produto não encontrado.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Digite um produto para procurar.");
    }//GEN-LAST:event_BTNProcurarActionPerformed
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNTListar;
    private javax.swing.JButton BNTOrgnizar;
    private javax.swing.JButton BTNAlterar;
    private javax.swing.JButton BTNApagar;
    private javax.swing.JButton BTNProcurar;
    private javax.swing.JButton BTNQuantidade;
    private javax.swing.JButton BTNlimpar;
    private javax.swing.JButton BTNsalvar;
    private javax.swing.JTextField TXTCodigo;
    private javax.swing.JTextField TXTCodigoEx;
    private javax.swing.JTextField TXTNovoPerfume;
    private javax.swing.JTextField TXTProcurar;
    private javax.swing.JTextArea TXTlista;
    private javax.swing.JTextField TXTperfume;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
